const userProfs = [
    { firstName: "Lelia", secondName: "Ricketson", age: "49" },
    { firstName: "James", secondName: "Nielsen", age: "35" },
    { firstName: "Ryan", secondName: "Wilson", age: "32" },
    { firstName: "Laura", secondName: "Yancey", age: "55" },
    { firstName: "William", secondName: "Wilson", age: "54" },
    { firstName: "Tom", secondName: "Killian", age: "41" },
    { firstName: "Toby", secondName: "Sanchez", age: "19" },
    { firstName: "Carol", secondName: "Fearon", age: "51" },
    { firstName: "Joann", secondName: "Sandoval", age: "23" },
    { firstName: "Veronica", secondName: "Sanchez", age: "62" },
    { firstName: "Stephan", secondName: "Taylor", age: "37" },
    { firstName: "Stephen", secondName: "Reyes", age: "64" },
    { firstName: "Allen", secondName: "Gibson", age: "35" },
    { firstName: "Stacy", secondName: "Epstein", age: "39" },
    { firstName: "Sally", secondName: "Hicks", age: "27" },
];
